# Generated by Django 2.2.26 on 2023-03-22 08:30

from django.db import migrations, models
import users.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_phone', models.CharField(max_length=15, unique=True, validators=[users.utils.validate_phone])),
                ('contact_email', models.EmailField(max_length=254)),
                ('legal_document', models.FileField(upload_to='')),
                ('regulation_body_account_id', models.FileField(upload_to='')),
            ],
        ),
    ]
