# Generated by Django 2.2.26 on 2023-03-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230322_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='verified_by',
        ),
    ]
