# Generated by Django 2.2.26 on 2023-03-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_organizationadmins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationAdmins',
            new_name='OrganizationUser',
        ),
    ]
