# Generated by Django 2.2.26 on 2023-03-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230323_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
