# Generated by Django 2.2.26 on 2023-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
