# Generated by Django 2.2.26 on 2023-03-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20230324_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizers',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.OrganizationUser'),
        ),
    ]
