# Generated by Django 2.2.26 on 2023-03-27 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_auto_20230327_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsvolunteers',
            old_name='events',
            new_name='event',
        ),
        migrations.AlterUniqueTogether(
            name='eventsvolunteers',
            unique_together={('event', 'volunteer')},
        ),
    ]
