# Generated by Django 2.2.26 on 2023-03-28 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20230328_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsvolunteershours',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EventsVolunteersCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('events_volunteers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventsVolunteers')),
            ],
        ),
    ]
