# Generated by Django 2.2.26 on 2023-03-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20230329_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_manger',
            new_name='campaign_manager',
        ),
    ]
