# Generated by Django 2.2.26 on 2023-03-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20230329_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='organization',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
