# Generated by Django 2.2.26 on 2023-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20230329_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsvolunteershours',
            name='daily_total_hours',
            field=models.FloatField(default=0),
        ),
    ]
