# Generated by Django 2.2.26 on 2023-04-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20230426_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
