# Generated by Django 2.2.26 on 2023-04-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_eventcertificate_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcertificate',
            old_name='event_id',
            new_name='event',
        ),
    ]
