# Generated by Django 2.2.26 on 2023-04-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20230430_0807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventsvolunteerscertification',
            unique_together={('events_volunteers', 'event_certeficate')},
        ),
    ]
